### ISSUE TITLE
Configuration for "bypass-billplz-page" method

### ISSUE THREAD

**Issue by ewallz** [wzul/Billplz-for-Minisite#1]
Hi & Salam, i've tried to implement bypass-billplz-page method for this code but to no success. Once form submitted always go to billplz page like usual not direct to bank.
What ive done:
set the reference_1_label in config file to "Bank Code"
and in form index.php I added the example bank code "ABB0233" (for affin) as value & name=reference_1

`<input class="form-control" name="reference_1" placeholder="" size="120" type="text" value="ABB0233" />`

Can you guide how to modify the current files here to be use for this purpose. Meaning to direct user only to single bank or method for payment. Thanks

**Comment by ewallz** [comment]
> 
> 
> Hi & Salam, i've tried to implement bypass-billplz-page method for this code but to no success. Once form submitted always go to billplz page like usual not direct to bank.
> What ive done:
> set the reference_1_label in config file to "Bank Code"
> and in form index.php I added the example bank code "ABB0233" (for affin) as value & name=reference_1
> 
> `<input class="form-control" name="reference_1" placeholder="" size="120" type="text" value="ABB0233" />`
> 
> Can you guide how to modify the current files here to be use for this purpose. Meaning to direct user only to single bank or method for payment. Thanks

Just manage to get it to works by adding the autosubmit=true on line 53 billplzpost.php like so:
`header('Location: ' . $rbody['url'].='?auto_submit=true');//direct-to-bank if method active`

**Comment by wzul** [comment]
Hi.

You may add this code before line 51 in this file https://github.com/Billplz/Billplz-for-Minisite/blob/master/billplzpost.php

```php
$rbody = $billplz->bypassBillplzPage($rbody);
```
